# Generated by Django 3.2.18 on 2023-03-05 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('volunteer_job', models.CharField(choices=[('Identify Animals', 'Identify Animals'), ('Fund Raiser', 'Fund Raiser'), ('Transcribe Field Notes', 'Transcribe Field Notes'), ('Help Researchers', 'Help Researchers')], default='', max_length=100)),
                ('work_time', models.CharField(choices=[('09:00', '09:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('17:00', '17:00'), ('19:00', '19:00')], default='', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
