# Generated by Django 3.2.18 on 2023-03-24 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_date', models.DateField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('volunteer_job', models.CharField(choices=[('Identify Animals', 'Identify Animals'), ('Fund Raiser', 'Fund Raiser'), ('Transcribe Field Notes', 'Transcribe Field Notes'), ('Help Researchers', 'Help Researchers')], max_length=100)),
                ('work_time', models.CharField(choices=[('09:00', '09:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('17:00', '17:00'), ('19:00', '19:00')], max_length=50)),
                ('animal_name', models.CharField(choices=[('Red Panda', 'Red Panda'), ('Artic Fox', 'Artic Fox'), ('Giant Panda', 'Giant Panda'), ('Red Wolf', 'Red Wolf'), ('Persian Fallow Dear', 'Persian Fallow Dear'), ('Saola', 'Saola'), ('Amur Leopard', 'Amur Leopard'), ('Arctic Beluga', 'Arctic Beluga'), ('Hyacinth Macaw', 'Hyacinth Macaw'), ('Vaquita', 'Vaquita'), ('Lemur', 'Lemur')], max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
                'unique_together': {('work_time', 'volunteer_job', 'animal_name', 'start_date')},
            },
        ),
    ]
