# Generated by Django 3.2.18 on 2023-03-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='animal_name',
            field=models.CharField(choices=[('Red Panda', 'Red Panda'), ('Artic Fox', 'Artic Fox'), ('Giant Panda', 'Giant Panda'), ('Red Wolf', 'Red Wolf'), ('Persian Fallow Dear', 'Persian Fallow Dear'), ('Saola', 'Saola'), ('Amur Leopard', 'Amur Leopard'), ('Arctic Beluga', 'Arctic Beluga'), ('Hyacinth Macaw', 'Hyacinth Macaw'), ('Vaquita', 'Vaquita'), ('Lemur', 'Lemur')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='volunteer_job',
            field=models.CharField(choices=[('Identify Animals', 'Identify Animals'), ('Fund Raiser', 'Fund Raiser'), ('Transcribe Field Notes', 'Transcribe Field Notes'), ('Help Researchers', 'Help Researchers')], max_length=30),
        ),
    ]
