# Generated by Django 3.2.18 on 2023-03-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'ordering': ['-name']},
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('work_time', 'volunteer_job')},
        ),
    ]
