# Generated by Django 3.2.18 on 2023-03-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230308_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together=set(),
        ),
    ]
