# Generated by Django 3.2.18 on 2023-03-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_enroll_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('work_time', 'volunteer_job')},
        ),
    ]
