# Generated by Django 3.2.18 on 2023-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_enroll_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='animal_name',
            field=models.CharField(choices=[('Red Panda', 'Red Panda'), ('Artic Fox', 'Artic Fox'), ('Steppe Eagle', 'Steppe Eagle'), ('Red Wolf', 'Red Wolf'), ('Persian Fallow Dear', 'Persian Fallow Dear'), ('Koala', 'Koala'), ('Wolverine', 'Wolverine')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enroll',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('work_time', 'volunteer_job', 'animal_name')},
        ),
    ]
