# Generated by Django 3.2.18 on 2023-03-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20230314_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='animal_name',
            field=models.CharField(choices=[('Red Panda', 'Red Panda'), ('Artic Fox', 'Artic Fox'), ('Steppe Eagle', 'Steppe Eagle'), ('Red Wolf', 'Red Wolf'), ('Persian Fallow Dear', 'Persian Fallow Dear'), ('Koala', 'Koala'), ('Wolverine', 'Wolverine')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='volunteer_job',
            field=models.CharField(choices=[('Identify Animals', 'Identify Animals'), ('Fund Raiser', 'Fund Raiser'), ('Transcribe Field Notes', 'Transcribe Field Notes'), ('Help Researchers', 'Help Researchers')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='work_time',
            field=models.CharField(choices=[('09:00', '09:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('17:00', '17:00'), ('19:00', '19:00')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('work_time', 'volunteer_job', 'animal_name', 'start_date')},
        ),
    ]
