# Generated by Django 3.2.18 on 2023-03-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20230319_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='animal_name',
            field=models.CharField(choices=[('Red Panda', 'Red Panda'), ('Artic Fox', 'Artic Fox'), ('Giant Panda', 'Giant Panda'), ('Red Wolf', 'Red Wolf'), ('Persian Fallow Dear', 'Persian Fallow Dear'), ('Saola', 'Saola'), ('Amur Leopard', 'Amur Leopard'), ('Arctic Beluga', 'Arctic Beluga'), ('Hyacinth Macaw', 'Hyacinth Macaw'), ('Vaquita', 'Vaquita'), ('Lemur', 'Lemur')], max_length=100),
        ),
    ]
