# Generated by Django 3.2.18 on 2023-03-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230323_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_on',
        ),
    ]
