# Generated by Django 3.2.18 on 2023-02-25 19:16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survival_cateogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogory', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('animal_cateogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.survival_cateogory')),
                ('animal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.animal')),
            ],
        ),
    ]
