# Generated by Django 3.2.18 on 2023-02-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
    ]
