# Generated by Django 3.2.18 on 2023-02-26 13:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_rename_programs_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
