# Generated by Django 3.2.18 on 2023-03-02 13:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20230226_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='survival_category',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
